<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>KeyboardControllerMode</AssemblyName>
    <RootNamespace>KeyboardControllerMode</RootNamespace>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Sts2Dir Condition="'$(Sts2Dir)' == ''">../game</Sts2Dir>
    <Sts2ManagedDir>$(Sts2Dir)/data_sts2_windows_x86_64</Sts2ManagedDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(Sts2ManagedDir)/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>$(Sts2ManagedDir)/GodotSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="sts2">
      <HintPath>$(Sts2ManagedDir)/sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
